spring.application.name=gerenciamentodesaude

# Config H2 (DB)

spring.h2.console.enable=true
spring.datasource.url=jdbc:h2:mem:dbapp

# ||
# spring.datasource.url=jdbc:h2:file./data

# Rota da dependencia costuma mudar em diferentes versoes
spring.datasource.driver.class.name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=senhaTeste

# Config JPA -> Hibernate

spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.dll=update
spring.jpa.show-sql=true