spring.application.name=health-management

# JDBC: Java Database Connector
spring.datasource.url=jdbc:h2:mem:database-name
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.database-plaform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.dll=update

# DEVELOPMENT
spring.jpa.show-sql=true

# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Path Base (Endpoints)
path.url=http://localhost:8080